# Generated by Django 5.2.8 on 2026-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('mantenimiento_acceso', 'MANTENIMIENTO: Ingreso al módulo'), ('mantenimiento_crear_orden', 'MANTENIMIENTO: Crear órdenes de trabajo'), ('mantenimiento_aprobar_orden', 'MANTENIMIENTO: Aprobar órdenes (Jefatura)'), ('mantenimiento_ver_reportes', 'MANTENIMIENTO: Ver reportes de mantenimiento')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='codigo',
            field=models.CharField(help_text='Código corto para referencias internas. Ej: FIN, LOG, IT', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilgrupo',
            name='es_gerencial',
            field=models.BooleanField(default=False, help_text='Si es True, este rol tiene capacidades de gestión sobre subordinados.'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True, help_text='Si es True, el frontend bloqueará el acceso al Dashboard hasta que cambie la clave.'),
        ),
        migrations.AlterField(
            model_name='pertenencia',
            name='permisos_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Excepciones específicas para este usuario en esta empresa (se suman al rol base).', to='auth.permission'),
        ),
    ]
